MenuHW/Controllers/DictionaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MenuHW.Controllers
{
    public class DictionaryController : Controller
    {
        static Dictionary<int, string> myDictionary = new Dictionary<int, string>();
        
        // GET: Dictionary
        public ActionResult Index()
        {
            ViewBag.MyDictionary = myDictionary;
            return View();
        }

        //add one entry in myDictionary
        public ActionResult AddOne()
        {
            myDictionary.Add(myDictionary.Count, "New Entry " + myDictionary.Count);
            ViewBag.MyDictionary = myDictionary;
            return View("Index");
        }

        //clear out previous entries and add 2000 new entries
        public ActionResult AddAlot()
        {
            for(int i = 0; i< 2000; i++)
            {
                myDictionary.Add(i, "New Entry");
            }

            ViewBag.MyDictionary = myDictionary;
            return View("Index");
        }

        public ActionResult Display()
        {
            foreach(KeyValuePair<int, string> dict in myDictionary)
            {
                ViewBag.MyDictionary = myDictionary;
            }

            return View("Index");
        }

        //delete all data in dictionary
        public ActionResult DeleteAll()
        {
            myDictionary.Clear();
            ViewBag.MyDictionary = myDictionary;
            return View("Index");
        }
    }
}

MenuHW/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MenuHW.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Exit()
        {
            return new RedirectResult("https://www.byu.edu/");
        }

    }
}

MenuHW/Controllers/QueueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MenuHW.Controllers
{
    public class QueueController : Controller
    {
        static Queue<string> myQueue = new Queue<string>();

        // GET: Queue
        public ActionResult Index()
        {
            ViewBag.MyQueue = myQueue;
            return View();
        }

        //add one entry in myQueue
        public ActionResult AddOne()
        {
            myQueue.Enqueue("New Entry " + (myQueue.Count + 1));
            ViewBag.MyQueue = myQueue;
            return View("Index");
        }

        //clear previous entries and add 2000 new entries
        public ActionResult AddAlot()
        {
            myQueue.Clear();

            for (var i = 0; i < 2000; i++)
            {
                myQueue.Enqueue("New Entry " + i);
            }

            ViewBag.MyQueue = myQueue;
            return View("Index");
        }

        //delete all data in queue
        public ActionResult DeleteAll()
        {
            myQueue.Clear();
            ViewBag.MyQueue = myQueue;
            return View("Index");
        }
    }
}

MenuHW/Controllers/StackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MenuHW.Controllers
{
    public class StackController : Controller
    {
        static Stack<string> myStack = new Stack<string>();

        // GET: Stack
        public ActionResult Index()
        {
            ViewBag.MyStack = myStack;
            return View();
        }

        //add one entry in myStack
        public ActionResult AddOne()
        {
            myStack.Push("New Entry " + (myStack.Count + 1));
            ViewBag.MyStack = myStack;
            return View("Index");
        }

        //clear previous entries and add 2000 new entries
        public ActionResult AddAlot()
        {
            myStack.Clear();

            for (var i = 0; i < 2000; i++)
            {
                myStack.Push("New Entry " + Convert.ToString(i++));
            }

            ViewBag.MyStack = myStack;

            return View("Index");
        }

        //delete all data in stack
        public ActionResult DeleteAll()
        {
            myStack.Clear();
            ViewBag.MyStack = myStack;

            return View("Index");
        }
    }
}

MenuHW/Views/Dictionary/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript" src="./lib/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="~/Content/bootstrap.min (2).css" rel="stylesheet" />
    <link href="~/Content/myStyle.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div id="sidenav" class="btn-group-vertical" data-toggle="buttons">
        <a href="@Url.Action("AddOne", "Dictionary")" class="btn btn-primary" type="button" role="button">Add one time to Dictionary</a>
        <a href="@Url.Action("AddAlot", "Dictionary")" class="btn btn-primary" type="button" role="button">Add Huge List of Items to Dictionary</a>
        <a href="@Url.Action("Index", "Dictionary")" class="btn btn-primary" type="button" role="button">Display Dictionary</a>
        <a href="@Url.Action("DeleteAll", "Dictionary")" class="btn btn-primary" type="button" role="button">Delete from Dictionary</a>
        <a href="@Url.Action("Index", "Dictionary")" class="btn btn-primary" type="button" role="button">Clear Dictionary</a>
        <a href="@Url.Action("Index", "Dictionary")" class="btn btn-primary" type="button" role="button">Search Dictionary</a>
        <a href="@Url.Action("Index", "Home")" class="btn btn-primary" type="button" role="button">Return to Main Menu</a>
    </div>
    <div id="newentry" class="center">
        @foreach (var sData in ViewBag.MyDictionary)
        {
            <p>@sData</p>
        }
    </div>
</body>
</html>

MenuHW/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript" src="./lib/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="~/Content/myStyle.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min (2).css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>Stack Index</title>
</head>
<body>
    <div class="jumbotron" style="margin-top: 30px">
        <h1 style="text-align: center">Data Structure is Fun :)</h1>
    </div>
    <div class="center" id="wrapper">
        <a href="@Url.Action("Index", "Queue")" type="button" role="button" class="btn btn-outline-secondary">Queue</a>
        <a href="@Url.Action("Index", "Dictionary")" type="button" role="button" class="btn btn-outline-secondary">Dictionary</a>
        <a href="@Url.Action("Index", "Stack")" type="button" role="button" class="btn btn-outline-secondary">Stack</a>
    </div>
</body>
</html>

MenuHW/Views/Queue/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript" src="./lib/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="~/Content/bootstrap.min (2).css" rel="stylesheet" />
    <link href="~/Content/myStyle.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div id="sidenav" class="btn-group-vertical" data-toggle="buttons">
        <a href="@Url.Action("AddOne", "Queue")" class="btn btn-primary" type="button" role="button">Add one time to Queue</a>
        <a href="@Url.Action("AddAlot", "Queue")" class="btn btn-primary" type="button" role="button">Add Huge List of Items to Queue</a>
        <a href="@Url.Action("Index", "Queue")" class="btn btn-primary" type="button" role="button">Display Queue</a>
        <a href="@Url.Action("DeleteAll", "Queue")" class="btn btn-primary" type="button" role="button">Delete from Queue</a>
        <a href="@Url.Action("Index", "Queue")" class="btn btn-primary" type="button" role="button">Clear Queue</a>
        <a href="@Url.Action("Index", "Queue")" class="btn btn-primary" type="button" role="button">Search Queue</a>
        <a href="@Url.Action("Index", "Home")" class="btn btn-primary" type="button" role="button">Return to Main Menu</a>
    </div>
    <div id="newentry" class="center">
        @foreach (var sData in ViewBag.MyQueue)
        {
            <p>@sData</p>
        }
    </div>
</body>
</html>

MenuHW/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Group 13</title>
    @*@Styles.Render("~/Content/bootstraptheme.min.css")
    @Scripts.Render("~/bundles/modernizr")*@
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <span class="navbar-brand">Group 13</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav mr-auto">
                <li class="nav-link">
                    <a href="@Url.Action("Index", "Stack")" class="w3-bar-item w3-button">Stack</a>
                </li>
                <li class="nav-link">
                    <a href="@Url.Action("Index", "Queue")" class="w3-bar-item w3-button">Queue</a>
                </li>
                <li class="nav-link">
                    <a href="@Url.Action("Index", "Dictionary")" class="w3-bar-item w3-button">Dictionary</a>
                </li>
                <li class="nav-link">
                    <a href="@Url.Action("Exit", "Home")" class="w3-bar-item w3-button">Exit</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Group 13.</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>

<style>
    a {
        color: white;
        text-decoration: none;
    }
</style>

MenuHW/Views/Stack/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript" src="./lib/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="~/Content/bootstrap.min (2).css" rel="stylesheet" />
    <link href="~/Content/myStyle.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div id="sidenav" class="btn-group-vertical" data-toggle="buttons">
        <a href="@Url.Action("AddOne", "Stack")" class="btn btn-primary" type="button" role="button">Add one time to Stack</a>
        <a href="@Url.Action("AddAlot", "Stack")" class="btn btn-primary" type="button" role="button">Add Huge List of Items to Stack</a>
        <a href="@Url.Action("Index", "Stack")" class="btn btn-primary" type="button" role="button">Display Stack</a>
        <a href="@Url.Action("DeleteAll", "Stack")" class="btn btn-primary" type="button" role="button">Delete from Stack</a>
        <a href="@Url.Action("Index", "Stack")" class="btn btn-primary" type="button" role="button">Clear Stack</a>
        <a href="@Url.Action("Index", "Stack")" class="btn btn-primary" type="button" role="button">Search Stack</a>
        <a href="@Url.Action("Index", "Home")" class="btn btn-primary" type="button" role="button">Return to Main Menu</a>
    </div>
    <div id="newentry" class="center">
        @foreach (var sData in ViewBag.MyStack)
        {
            <span>@sData &nbsp;</span>
        }
    </div>   
</body>
</html>